name: Varys
on:
  push:
    paths:
    - "test/publickeys/*"

jobs:
  varys:
    name: Varys
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0b496e91ec7ae4428c3ed2eeb4c3a40df431f2cc
      - name: Run Varys
        uses: hfaulds/varys@master
        with:
          publicKeyDir: test/publickeys
          secret: ${{ secrets.test_secret }}
          output: test/secret
          githubToken: ${{ secrets.GITHUB_TOKEN }}
