name: Varys
on:
  push:
    paths-ignore:
    - "test/publickeys/*"

jobs:
  varys:
    name: Varys
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install
      - name: Run Varys
        uses: hfaulds/varys@5633a4ccc958c2bd4c1a2bdf124a7d2d17c592f9
        with:
          publicKeyDir: test/publickeys
          secret: ${{ secrets.test_secret }}
          output: test/secret
